# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(774, 698)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(510, 40, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.filetype_combo_box = QtWidgets.QComboBox(Dialog)
        self.filetype_combo_box.setGeometry(QtCore.QRect(30, 10, 69, 22))
        self.filetype_combo_box.setObjectName("filetype_combo_box")
        self.url_input_block = QtWidgets.QLineEdit(Dialog)
        self.url_input_block.setGeometry(QtCore.QRect(30, 40, 471, 20))
        self.url_input_block.setObjectName("url_input_block")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Url Send"))
